title: 128 Construction Consultants
email: scott@128constructionconsultants.com
phone: 555-555-5555
url: "https://128constructionconsultants.com"
baseurl: "sdecurti.github.io"

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
