title: 128 Construction Consultants Put Something New
email: scott@128constructionconsulstants.com
url: ""
baseurl: ""

plugins:
  - jekyll-postcss

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
