title: 128 Construction Consultants
email: scott@128constructionconsulstants.com
phone: 555-555-5555
url: ""
baseurl: ""

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
