title: 128 Construction Consultants
email: scott@128constructionconsulstants.com
baseurl: /sdecurti.github.io
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
sass:
  load_paths:
    - _sass
    - node_modules
include: ["node_modules/tailwindcss"]
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- yarn.lock
- package-lock.json
- README.md
- postcss.config.js
- purgecss.config.js
- netlify.toml
- bin
- .gitignore