title: 128 Construction Consultants
email: scott@128constructionconsulstants.com
url: ""
baseurl: "/sdecurti.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-postcss
sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
